// ===== Dados dos projetos (cases) =====
// Categorias válidas: 'tbm' | 'mineracao' | 'pipe-jacking' | 'ferrovias'
// Regiões válidas: 'asia' | 'europa' | 'africa' | 'americas'
// slug é usado na URL: /projetos/<slug>

export const CASE_CATEGORIES = [
  { key: 'tbm', label: 'Tuneladoras (TBM)' },
  { key: 'mineracao', label: 'Mineração' },
  { key: 'pipe-jacking', label: 'Pipe jacking' },
  { key: 'ferrovias', label: 'Ferrovias' },
];

export const CASE_REGIONS = [
  { key: 'asia', label: 'Ásia' },
  { key: 'europa', label: 'Europa' },
  { key: 'africa', label: 'África' },
  { key: 'americas', label: 'Américas' },
];

export const CASES = [
  {
    slug: 'tunel-cabos-seosan',
    title: 'Túnel de cabos de Seosan',
    location: 'Seosan e Grande Seul, Coreia do Sul',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/tunel-cabos-seosan.jpg',
    summary: 'Túnel para instalação de linha de transmissão elétrica em ambiente urbano e periurbano.',
  },
  {
    slug: 'rodovia-sibiu-pitesti-poiana',
    title: 'Rodovia Sibiu–Pitesti, Túnel Poiana (Lote 3)',
    location: 'Cornetu a Tigveni, Romênia',
    region: 'europa',
    category: 'tbm',
    image: '/images/cases/rodovia-sibiu-pitesti-poiana.jpg',
    summary: 'Túnel rodoviário em maciço montanhoso, parte de um corredor viário estratégico.',
  },
  {
    slug: 'mina-chambishi-zambia',
    title: 'Corpo de minério sudeste de Chambishi',
    location: 'Chambishi, Zâmbia',
    region: 'africa',
    category: 'mineracao',
    image: '/images/cases/mina-chambishi-zambia.jpg',
    summary: 'Desenvolvimento de mina subterrânea para acesso a corpo de minério de cobre.',
  },
  {
    slug: 'tunel-ferroviario-verona-fortezza',
    title: 'Túnel ferroviário Verona–Fortezza',
    location: 'Verona a Fortezza, Itália',
    region: 'europa',
    category: 'ferrovias',
    image: '/images/cases/tunel-ferroviario-verona-fortezza.jpg',
    summary: 'Túnel ferroviário de alta capacidade integrado a corredor de transporte europeu.',
  },
  {
    slug: 'tunel-canal-elahera',
    title: 'Túnel de desvio do Canal Upper Elahera',
    location: 'Sri Lanka',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/tunel-canal-elahera.jpg',
    summary: 'Túnel de adução/desvio de água com TBM de duplo escudo para irrigação.',
  },
  {
    slug: 'tunel-yangtze-yancheng-yixing',
    title: 'Túnel do Yangtze — Ferrovia de alta velocidade Yancheng–Yixing',
    location: 'Travessia do rio Yangtze, China',
    region: 'asia',
    category: 'ferrovias',
    image: '/images/cases/tunel-yangtze-yancheng-yixing.jpg',
    summary: 'Travessia subaquática de rio para linha ferroviária de alta velocidade.',
  },
  {
    slug: 'metro-circular-epb-grande-diametro',
    title: 'Metrô circular — TBM EPB de grande diâmetro',
    location: 'Europa Oriental',
    region: 'europa',
    category: 'tbm',
    image: '/images/cases/metro-circular-epb-grande-diametro.jpg',
    summary: 'Linha circular de metrô escavada com TBM EPB de grande diâmetro em meio urbano.',
  },
  {
    slug: 'transposicao-yangtze-han',
    title: 'Transposição de água Yangtze–Rio Han',
    location: 'China central',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/transposicao-yangtze-han.jpg',
    summary: 'Túnel de transposição hídrica de longa extensão para abastecimento.',
  },
  {
    slug: 'pipe-roof-estuario-sanya',
    title: 'Passagem do estuário do rio Sanya (pipe-roof)',
    location: 'Sanya, Hainan, China',
    region: 'asia',
    category: 'pipe-jacking',
    image: '/images/cases/pipe-roof-estuario-sanya.jpg',
    summary: 'Travessia com técnica de pipe-roof / cravação de tubos sob estuário.',
  },
  {
    slug: 'tunel-subaquatico-perola',
    title: 'Túnel ferroviário subaquático do estuário do rio das Pérolas',
    location: 'Estuário do rio das Pérolas, China',
    region: 'asia',
    category: 'ferrovias',
    image: '/images/cases/tunel-subaquatico-perola.jpg',
    summary: 'Túnel ferroviário submerso em travessia de estuário de grande porte.',
  },
  {
    slug: 'tunel-ferroviario-polonia-1042',
    title: 'Túnel ferroviário Polônia 1042',
    location: 'Polônia',
    region: 'europa',
    category: 'ferrovias',
    image: '/images/cases/tunel-ferroviario-polonia-1042.jpg',
    summary: 'Túnel ferroviário integrado à modernização da malha nacional.',
  },
  {
    slug: 'tunel-espiral-rocha-dura',
    title: 'Túnel de acesso em espiral com TBM de rocha dura',
    location: 'China',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/tunel-espiral-rocha-dura.jpg',
    summary: 'Túnel de acesso helicoidal escavado em rocha dura com TBM.',
  },
  {
    slug: 'tunel-rodoviario-haitai-yangtze',
    title: 'Túnel rodoviário Haitai do rio Yangtze',
    location: 'Nantong, Jiangsu, China',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/tunel-rodoviario-haitai-yangtze.jpg',
    summary: 'Túnel rodoviário de grande diâmetro sob o rio Yangtze.',
  },
  {
    slug: 'tunel-drenagem-songyang',
    title: 'Túnel de drenagem da usina reversível de Songyang',
    location: 'Songyang, Zhejiang, China',
    region: 'asia',
    category: 'tbm',
    image: '/images/cases/tunel-drenagem-songyang.jpg',
    summary: 'Túnel de drenagem para usina hidrelétrica reversível (pumped storage).',
  },
  {
    slug: 'metro-santiago-linhas-7-8',
    title: 'Metrô de Santiago — Linhas 7 e 8',
    location: 'Santiago, Chile',
    region: 'americas',
    category: 'tbm',
    image: '/images/cases/metro-santiago-linhas-7-8.jpg',
    summary: 'Expansão da rede de metrô urbano com múltiplas tuneladoras.',
  },
];
